<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Flequery" Version="0.3.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.11" />
    <PackageReference Include="Monq.Core.MvcExtensions" Version="4.1.0" />
    <PackageReference Include="Monq.Core.Paging" Version="5.1.0" />
    <PackageReference Include="Monq.Core.Paging.Models" Version="5.0.0" />
  </ItemGroup>

</Project>
