// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Prism.Core.WebApi.Database;

#nullable disable

namespace Prism.Core.WebApi.Migrations
{
    [DbContext(typeof(PrismContext))]
    [Migration("20260831171737_m001_Initial")]
    partial class m001_Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Prism.Core.WebApi.Models.Rate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Color")
                        .HasColumnType("integer")
                        .HasColumnName("color");

                    b.Property<char>("Letter")
                        .HasColumnType("character(1)")
                        .HasColumnName("letter");

                    b.Property<int>("Value")
                        .HasColumnType("integer")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.ToTable("rates", (string)null);
                });

            modelBuilder.Entity("Prism.Core.WebApi.Models.Record", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ThemeId")
                        .HasColumnType("uuid")
                        .HasColumnName("theme_id");

                    b.HasKey("Id");

                    b.ToTable("records", (string)null);
                });

            modelBuilder.Entity("Prism.Core.WebApi.Models.RecordValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("RecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("record_id");

                    b.Property<Guid>("ThemeFieldId")
                        .HasColumnType("uuid")
                        .HasColumnName("theme_field_id");

                    b.HasKey("Id");

                    b.ToTable("record_values", (string)null);
                });

            modelBuilder.Entity("Prism.Core.WebApi.Models.RecordValueVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool?>("BoolValue")
                        .HasColumnType("boolean")
                        .HasColumnName("bool_value");

                    b.Property<DateTime?>("DateValue")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_value");

                    b.Property<double?>("DoubleValue")
                        .HasColumnType("double precision")
                        .HasColumnName("double_value");

                    b.Property<int?>("IntValue")
                        .HasColumnType("integer")
                        .HasColumnName("int_value");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_accepted");

                    b.Property<Guid>("RecordValueId")
                        .HasColumnType("uuid")
                        .HasColumnName("record_value_id");

                    b.Property<string>("StringValue")
                        .HasColumnType("text")
                        .HasColumnName("string_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("WriteDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("write_date");

                    b.HasKey("Id");

                    b.ToTable("record_value_versions", (string)null);
                });

            modelBuilder.Entity("Prism.Core.WebApi.Models.RecordVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_accepted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("RecordId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("WriteDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("write_date");

                    b.HasKey("Id");

                    b.ToTable("record_versions", (string)null);
                });

            modelBuilder.Entity("Prism.Core.WebApi.Models.Theme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.HasKey("Id");

                    b.ToTable("themes", (string)null);
                });

            modelBuilder.Entity("Prism.Core.WebApi.Models.ThemeField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("ThemeId")
                        .HasColumnType("uuid")
                        .HasColumnName("theme_id");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("theme_fields", (string)null);
                });

            modelBuilder.Entity("Prism.Core.WebApi.Models.ThemeFieldVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_accepted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<Guid>("ThemeFieldId")
                        .HasColumnType("uuid")
                        .HasColumnName("theme_field_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("WriteDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("write_date");

                    b.HasKey("Id");

                    b.ToTable("theme_field_versions", (string)null);
                });

            modelBuilder.Entity("Prism.Core.WebApi.Models.ThemeVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_accepted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<Guid>("ThemeId")
                        .HasColumnType("uuid")
                        .HasColumnName("theme_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("WriteDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("write_date");

                    b.HasKey("Id");

                    b.ToTable("theme_versions", (string)null);
                });

            modelBuilder.Entity("Prism.Core.WebApi.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<short>("Role")
                        .HasColumnType("smallint")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Prism.Core.WebApi.Models.UserRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("RateId")
                        .HasColumnType("uuid")
                        .HasColumnName("rate_id");

                    b.Property<Guid>("RecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("record_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("user_rates", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
