// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Prism.Core.DataAccess.Database;

#nullable disable

namespace Prism.Core.DataAccess.Migrations
{
    [DbContext(typeof(PrismContext))]
    [Migration("20260901181821_m003_AddIsDeletedToThemeVersionAndThemeFieldVersion")]
    partial class m003_AddIsDeletedToThemeVersionAndThemeFieldVersion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Prism.Core.Domain.Models.Rate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Color")
                        .HasColumnType("integer")
                        .HasColumnName("color");

                    b.Property<char>("Letter")
                        .HasColumnType("character(1)")
                        .HasColumnName("letter");

                    b.Property<int>("Value")
                        .HasColumnType("integer")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.ToTable("rates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("34a688e2-472b-41aa-b9b0-fa1331b2c5fe"),
                            Color = -7077677,
                            Letter = 'F',
                            Value = 1
                        },
                        new
                        {
                            Id = new Guid("180ae0be-d8dd-415c-b1bb-d1ca81543187"),
                            Color = -7077677,
                            Letter = 'F',
                            Value = 2
                        },
                        new
                        {
                            Id = new Guid("f1229048-2cd3-4b74-87a8-90062776a481"),
                            Color = -7077677,
                            Letter = 'F',
                            Value = 3
                        },
                        new
                        {
                            Id = new Guid("13524847-c476-41d1-8834-84db11b4a05d"),
                            Color = -16776961,
                            Letter = 'E',
                            Value = 4
                        },
                        new
                        {
                            Id = new Guid("5a606102-34ec-4b30-89aa-47e1bdccfea6"),
                            Color = -16711681,
                            Letter = 'D',
                            Value = 5
                        },
                        new
                        {
                            Id = new Guid("3500e2f4-16f0-486f-b75f-147687573ab8"),
                            Color = -16744448,
                            Letter = 'C',
                            Value = 6
                        },
                        new
                        {
                            Id = new Guid("57c0097b-a044-41d4-a6a7-8b500f7cf08d"),
                            Color = -256,
                            Letter = 'B',
                            Value = 7
                        },
                        new
                        {
                            Id = new Guid("a757745b-c04a-4479-aca4-5c64ff8625d4"),
                            Color = -23296,
                            Letter = 'A',
                            Value = 8
                        },
                        new
                        {
                            Id = new Guid("17818146-13fe-4569-b59a-c82828e550bf"),
                            Color = -23296,
                            Letter = 'A',
                            Value = 9
                        },
                        new
                        {
                            Id = new Guid("7d3bdd20-b87c-4344-abe3-30dd224fb0db"),
                            Color = -65536,
                            Letter = 'S',
                            Value = 10
                        });
                });

            modelBuilder.Entity("Prism.Core.Domain.Models.Record", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ThemeId")
                        .HasColumnType("uuid")
                        .HasColumnName("theme_id");

                    b.HasKey("Id");

                    b.ToTable("records", (string)null);
                });

            modelBuilder.Entity("Prism.Core.Domain.Models.RecordValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("RecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("record_id");

                    b.Property<Guid>("ThemeFieldId")
                        .HasColumnType("uuid")
                        .HasColumnName("theme_field_id");

                    b.HasKey("Id");

                    b.ToTable("record_values", (string)null);
                });

            modelBuilder.Entity("Prism.Core.Domain.Models.RecordValueVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool?>("BoolValue")
                        .HasColumnType("boolean")
                        .HasColumnName("bool_value");

                    b.Property<DateTime?>("DateValue")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_value");

                    b.Property<double?>("DoubleValue")
                        .HasColumnType("double precision")
                        .HasColumnName("double_value");

                    b.Property<int?>("IntValue")
                        .HasColumnType("integer")
                        .HasColumnName("int_value");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_accepted");

                    b.Property<Guid>("RecordValueId")
                        .HasColumnType("uuid")
                        .HasColumnName("record_value_id");

                    b.Property<string>("StringValue")
                        .HasColumnType("text")
                        .HasColumnName("string_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("WriteDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("write_date");

                    b.HasKey("Id");

                    b.ToTable("record_value_versions", (string)null);
                });

            modelBuilder.Entity("Prism.Core.Domain.Models.RecordVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_accepted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("RecordId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("WriteDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("write_date");

                    b.HasKey("Id");

                    b.ToTable("record_versions", (string)null);
                });

            modelBuilder.Entity("Prism.Core.Domain.Models.Theme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.HasKey("Id");

                    b.ToTable("themes", (string)null);
                });

            modelBuilder.Entity("Prism.Core.Domain.Models.ThemeField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ThemeId")
                        .HasColumnType("uuid")
                        .HasColumnName("theme_id");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("theme_fields", (string)null);
                });

            modelBuilder.Entity("Prism.Core.Domain.Models.ThemeFieldVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_accepted");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<Guid>("ThemeFieldId")
                        .HasColumnType("uuid")
                        .HasColumnName("theme_field_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("WriteDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("write_date");

                    b.HasKey("Id");

                    b.ToTable("theme_field_versions", (string)null);
                });

            modelBuilder.Entity("Prism.Core.Domain.Models.ThemeVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_accepted");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<Guid>("ThemeId")
                        .HasColumnType("uuid")
                        .HasColumnName("theme_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("WriteDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("write_date");

                    b.HasKey("Id");

                    b.ToTable("theme_versions", (string)null);
                });

            modelBuilder.Entity("Prism.Core.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<short>("Role")
                        .HasColumnType("smallint")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Prism.Core.Domain.Models.UserRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("RateId")
                        .HasColumnType("uuid")
                        .HasColumnName("rate_id");

                    b.Property<Guid>("RecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("record_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("user_rates", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
